version: '1.0'

services:
  terobyte:
    image: elsama/terobyte:latest
    container_name: terobyte
    ports:
      - "8080:80"
    environment:
      - TEROBYTE_PASSWORD=password
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
    restart: always
